name: articlest
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.1+dev

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.6.2
  shared_preferences: ^0.5.1 # 简单 kv 持久化存储
  sqflite: ^1.1.0 # 数据库持久化存储
  path_provider: ^0.5.0
  dio: ^2.0.0 # 网络请求
  rxdart: ^0.20.0 # Reactive

  fluintl: 0.1.2 # 国际化
  flutter_spinkit: '^3.1.0' # loading
  flutter_html: ^0.9.4 # 展示 html
  flutter_webview_plugin: ^0.3.0 # 显示网页
  intro_slider: ^1.1.4 # 初始化介绍页面

  json_annotation: 2.0.0

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2 # 修改应用 logo

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  json_serializable: 2.0.2 # json 序列化
  flutter_launcher_icons: ^0.7.0 # 修改应用 icon

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/initDB.sql
    - assets/images/login_logo.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

flutter_icons:
  image_path: 'assets/icon/icon.png'
  # image_path_android: 'assets/icon/icon-android.png'
  # image_path_ios: 'assets/icon/icon.png'
  android: true
  ios: true
